# Generated by Django 2.1.7 on 2019-02-15 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_name', models.CharField(max_length=50)),
                ('server_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_status', models.CharField(max_length=10)),
                ('server_environment', models.CharField(max_length=10)),
                ('server_function', models.CharField(max_length=20)),
                ('server_location', models.CharField(max_length=20)),
                ('ts_ops_mgr', models.CharField(max_length=50)),
                ('ts_ops_mgr_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tid', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('team_owner', models.CharField(max_length=100)),
                ('team_owner_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('ts_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('ts_name', models.CharField(max_length=100)),
                ('ts_ops_mgr', models.CharField(max_length=100)),
                ('ts_ops_mgr_email', models.CharField(max_length=100)),
                ('ts_dev_mgr', models.CharField(max_length=100)),
                ('ts_dev_mgr_email', models.CharField(max_length=100)),
                ('ts_qa_mgr', models.CharField(max_length=100)),
                ('ts_qa_mgr_email', models.CharField(max_length=100)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Team')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Team'),
        ),
        migrations.AddField(
            model_name='server',
            name='ts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.TechnicalService'),
        ),
    ]
